### ISSUE TITLE
Support for New-Session?

### ISSUE THREAD

**Issue by Tuumke** [andysvints/ExchangeOnlineShell#3]
Is it possible to setup a session with this?
I'm getting so tired of each time filling in my credentials (since im testing new script, i have to do this evert 5 / 6 minutes.. so annoying...

**Comment by andysvints** [comment]
Could you please provide more details?
Like what exactly are you trying to accomplish preferable with steps.
If your account has MFA enabled you cannot create session using New-Session cmdlet.

Thank you.

**Comment by Tuumke** [comment]
Uhm, i was trying to create a session so we would'nt have to login each time. Was trying to do something like
```
$session = Connect-ExchangeOnlineShell 
New-PSSession = $session
```
But i figured out with the latest version if you don't disconnect the session with command, it stays open. So we just had to check if session was online in our script :) problem fixed

**Comment by andysvints** [comment]
Glad to hear that you figured out. 
BTW useful workaround will definitely keep it in mind.
Thanks a lot for sharing
