### ISSUE TITLE
Problem when a proxy is used

### ISSUE THREAD

**Issue by GillesT78** [andysvints/ExchangeOnlineShell#8]
On line 191, you have a break that I don’t understand : 
            if($Proxy.ProxyEnable){
                Write-Verbose "Proxy Settings have been detected"
                $ProxyUsed=$true
                break
            }else{
                Write-Verbose "No Proxy Settings detected"
                $ProxyUsed=$false
            }

I think "break" has to be removed

**Comment by andysvints** [comment]
Thanks a lot for pointing it out.
You are correct break should be removed.
I've fixed it in latest release.
